[workspace]

members = [
    ".templates/rust",
    "lib/rust-aoc-common-lib",
    "day-01/drew-rust",
    "day-02/drew-rust",
    "day-03/drew-rust",
    "day-04/drew-rust",
    "day-05/drew-rust",
]
